"""users routes"""
from flask import current_app as app, jsonify, request
from models import MemTutorialData, BaseObject, db
from sqlalchemy.sql.expression import func

@app.route('/mem_tutorial_data/<user_id>', methods=['POST', 'GET'])
def create_mem_tutorial_data(user_id):
    content = request.json
    mem_tut = MemTutorialData()
    mem_tut.prolificID      = str(content.get('prolificID'))
    mem_tut.studyID      = str(content.get('studyID'))
    mem_tut.sessionID      = str(content.get('sessionID'))
    mem_tut.userID      = str(content.get('userID'))
    mem_tut.condition      = str(content.get('condition'))
    mem_tut.date        = str(content.get('date'))
    mem_tut.startTime   = str(content.get('startTime'))
    mem_tut.section    = str(content.get('section'))
    mem_tut.sectionTime    = str(content.get('sectionTime'))
    mem_tut.trialNum = str(content.get('trialNum'))
    mem_tut.tutorialTry = str(content.get('tutorialTry'))
    mem_tut.blockCond    = str(content.get('blockCond'))
    mem_tut.choicePos    = str(content.get('choicePos'))
    mem_tut.choiceCor    = str(content.get('choiceCor'))
    
    mem_tut.trialTime  = str(content.get('trialTime'))
    mem_tut.fixTime   = str(content.get('fixTime'))
    mem_tut.stimTime    = str(content.get('stimTime'))
    mem_tut.encodeTime    = str(content.get('encodeTime'))
    mem_tut.respTime  = str(content.get('respTime'))
    mem_tut.respFbTime     = str(content.get('respFbTime'))
    mem_tut.rewFbTime  = str(content.get('rewFbTime'))
    mem_tut.confTime    = str(content.get('confTime'))
    mem_tut.responseKey    = str(content.get('responseKey'))
    mem_tut.choice = str(content.get('choice'))
    mem_tut.correct = str(content.get('correct'))
    mem_tut.correctMat = str(content.get('correctMat'))
    mem_tut.correctPer = str(content.get('correctPer'))
    mem_tut.confLevel  = str(content.get('confLevel'))

    mem_tut.stimNum  = str(content.get('stimNum'))
    mem_tut.responseMatrix  = str(content.get('responseMatrix'))
    mem_tut.reversals = str(content.get('reversals'))
    mem_tut.stairDir     = str(content.get('stairDir'))

    mem_tut.stimNumEasy = str(content.get('stimNumEasy'))
    mem_tut.correctMatEasy = str(content.get('correctMatEasy'))
    mem_tut.correctPerEasy = str(content.get('correctPerEasy'))
    mem_tut.responseMatrixEasy  = str(content.get('responseMatrixEasy'))
    mem_tut.stairCountEasy  = str(content.get('stairCountEasy'))
    mem_tut.stairDirEasy  = str(content.get('stairDirEasy'))

    mem_tut.stimNumHard  = str(content.get('stimNumHard'))
    mem_tut.correctMatHard  = str(content.get('correctMatHard'))
    mem_tut.correctPerHard = str(content.get('correctPerHard'))
    mem_tut.responseMatrixHard     = str(content.get('responseMatrixHard'))
    mem_tut.stairCountHard  = str(content.get('stairCountHard'))
    mem_tut.stairDirHard     = str(content.get('stairDirHard'))

    mem_tut.stimPick  = str(content.get('stimPick'))
    mem_tut.stimWordPick  = str(content.get('stimWordPick'))
    mem_tut.stimShown     = str(content.get('stimShown'))
    mem_tut.stimWordShown  = str(content.get('stimWordShown'))
    mem_tut.choiceShownWordStim1 = str(content.get('choiceShownWordStim1'))
    mem_tut.choiceShownWordStim2     = str(content.get('choiceShownWordStim2'))
    mem_tut.choiceShownWordLeft = str(content.get('choiceShownWordLeft'))
    mem_tut.choiceShownWordRight     = str(content.get('choiceShownWordRight'))

    BaseObject.check_and_save(mem_tut)
    result = dict({"success": "yes"})
    return jsonify(result)
