"""users routes"""
from flask import current_app as app, jsonify, request
from models import PsychQuiz, BaseObject, db
from sqlalchemy.sql.expression import func

@app.route('/psych_quiz/<user_id>', methods=['POST', 'GET'])
def create_psych_data(user_id):
    content = request.json
    psych_quiz = PsychQuiz()
    psych_quiz.prolificID = str(content['prolificID'])
    psych_quiz.userID = str(content['userID'])
    psych_quiz.condition = str(content['condition'])
    psych_quiz.date = str(content['date'])
    psych_quiz.startTime = str(content['startTime'])
    psych_quiz.section = str(content['section'])
    psych_quiz.sectionTime = str(content['sectionTime'])
    psych_quiz.qnTimeStart = str(content['qnTimeStart'])
    psych_quiz.qnTimeEnd = str(content['qnTimeEnd'])
    psych_quiz.PgFinish_demo = str(content['PgFinish_demo'])
    psych_quiz.PgFinish_AES = str(content['PgFinish_AES'])
    psych_quiz.PgFinish_AUDIT = str(content['PgFinish_AUDIT'])
    psych_quiz.PgFinish_BIS11 = str(content['PgFinish_BIS11'])
    psych_quiz.PgFinish_EAT26 = str(content['PgFinish_EAT26'])
    psych_quiz.PgFinish_GSE = str(content['PgFinish_GSE'])
    psych_quiz.PgFinish_LSAS = str(content['PgFinish_LSAS'])
    psych_quiz.PgFinish_OCIR = str(content['PgFinish_OCIR'])
    psych_quiz.PgFinish_RSE = str(content['PgFinish_RSE'])
    psych_quiz.PgFinish_STAIY2 = str(content['PgFinish_STAIY2'])
    psych_quiz.PgFinish_SDS = str(content['PgFinish_SDS'])
    psych_quiz.PgFinish_SSMS = str(content['PgFinish_SSMS'])
    psych_quiz.PgFinish_IQ_text= str(content['PgFinish_IQ_text'])
    psych_quiz.PgFinish_IQ_image = str(content['PgFinish_IQ_image'])
    psych_quiz.PgRT_demo = str(content['PgRT_demo'])
    psych_quiz.PgRT_AES = str(content['PgRT_AES'])
    psych_quiz.PgRT_AUDIT = str(content['PgRT_AUDIT'])
    psych_quiz.PgRT_BIS11 = str(content['PgRT_BIS11'])
    psych_quiz.PgRT_EAT26 = str(content['PgRT_EAT26'])
    psych_quiz.PgRT_GSE = str(content['PgRT_GSE'])
    psych_quiz.PgRT_LSAS = str(content['PgRT_LSAS'])
    psych_quiz.PgRT_OCIR = str(content['PgRT_OCIR'])
    psych_quiz.PgRT_RSE = str(content['PgRT_RSE'])
    psych_quiz.PgRT_STAIY2 = str(content['PgRT_STAIY2'])
    psych_quiz.PgRT_SDS = str(content['PgRT_SDS'])
    psych_quiz.PgRT_SSMS = str(content['PgRT_SSMS'])
    psych_quiz.PgRT_IQ_text= str(content['PgRT_IQ_text'])
    psych_quiz.PgRT_IQ_image = str(content['PgRT_IQ_image'])
    psych_quiz.age = str(content['age'])
    psych_quiz.gender = str(content['gender'])
    psych_quiz.AES = str(content['AES'])
    psych_quiz.BIS11 = str(content['BIS11'])
    psych_quiz.EAT26 = str(content['EAT26'])
    psych_quiz.GSE = str(content['GSE'])
    psych_quiz.LSAS = str(content['LSAS'])
    psych_quiz.OCIR = str(content['OCIR'])
    psych_quiz.RSE = str(content['RSE'])
    psych_quiz.STAIY2 = str(content['STAIY2'])
    psych_quiz.SDS = str(content['SDS'])
    psych_quiz.SSMS = str(content['SSMS'])
    psych_quiz.AUDIT_1 = str(content['AUDIT_1'])
    psych_quiz.AUDIT_2 = str(content['AUDIT_2'])
    psych_quiz.AUDIT_3 = str(content['AUDIT_3'])
    psych_quiz.AUDIT_4 = str(content['AUDIT_4'])
    psych_quiz.AUDIT_5 = str(content['AUDIT_5'])
    psych_quiz.AUDIT_6 = str(content['AUDIT_6'])
    psych_quiz.AUDIT_7 = str(content['AUDIT_7'])
    psych_quiz.AUDIT_8 = str(content['AUDIT_8'])
    psych_quiz.AUDIT_9 = str(content['AUDIT_9'])
    psych_quiz.AUDIT_10 = str(content['AUDIT_10'])
    psych_quiz.AUDIT_11 = str(content['AUDIT_11'])
    psych_quiz.AUDIT_12 = str(content['AUDIT_12'])
    psych_quiz.AUDIT_13 = str(content['AUDIT_13'])
    psych_quiz.IQ_1= str(content['IQ_1'])
    psych_quiz.IQ_2= str(content['IQ_2'])
    psych_quiz.IQ_3= str(content['IQ_3'])
    psych_quiz.IQ_4= str(content['IQ_4'])
    psych_quiz.IQ_5= str(content['IQ_5'])
    psych_quiz.IQ_6= str(content['IQ_6'])
    psych_quiz.IQ_7= str(content['IQ_7'])
    psych_quiz.IQ_8= str(content['IQ_8'])
    psych_quiz.IQimage_1= str(content['IQimage_1'])
    psych_quiz.IQimage_2= str(content['IQimage_2'])
    psych_quiz.IQimage_3= str(content['IQimage_3'])
    psych_quiz.IQimage_4= str(content['IQimage_4'])
    psych_quiz.IQimage_5= str(content['IQimage_5'])
    psych_quiz.IQimage_6= str(content['IQimage_6'])
    psych_quiz.IQimage_7= str(content['IQimage_7'])
    psych_quiz.IQimage_8= str(content['IQimage_8'])

    BaseObject.check_and_save(psych_quiz)
    result = dict({"success": "yes"})
    return jsonify(result)
